version: "3.9"
services: 
    web01:
        build: 
            context: ./
            dockerfile: ./web01.Dockerfile
            args:
                - TIMEZONE=${TIMEZONE}
                - LINUX_USER_PASSWORD=${LINUX_USER_PASSWORD}
        hostname: web01.${PUBLIC_DOMAIN}
        restart: on-failure
        ports:
            - "${PUBLIC_ADDRESS}:80:80"
            - "${PUBLIC_ADDRESS}:443:443"
            - "${PUBLIC_ADDRESS}:22220:22"
            - "${PUBLIC_ADDRESS}:47080:7080"
        depends_on:
            - jsvc
            - redis
            - mariadb
        volumes:
            - srv:/srv
            - docs:${PDF_DOCUMENTS_DIR}
            - ./web01/conf:/usr/local/lsws/conf
            - w1_logs:/var/log
            - shared_uds:/run/shared
        environment:
            PDF_DOCUMENTS_DIR: ${PDF_DOCUMENTS_DIR}
            OLS_ADMIN_PASSWORD: ${OLS_ADMIN_PASSWORD}
            OLS_ADMIN_USERNAME: ${OLS_ADMIN_USERNAME}
    jsvc:
        build: 
            context: ./
            dockerfile: ./jsvc.Dockerfile
            args:
                - TIMEZONE=${TIMEZONE}
                - LINUX_USER_PASSWORD=${LINUX_USER_PASSWORD}
        hostname: j01.${PUBLIC_DOMAIN}
        ports:
            - "${PUBLIC_ADDRESS}:22221:22"
        restart: on-failure
        depends_on:
            - mariadb
        volumes:
            - jms:/opt/requisigner/dev
            - srv:/srv
            - docs:${PDF_DOCUMENTS_DIR}
            - shared_uds:/run/shared
    redis:
        image: redis:latest
        hostname: r01.${PUBLIC_DOMAIN}
        volumes:
            - redis_logs:/var/log
    mariadb:
        image: mariadb:latest
        hostname: db01.${PUBLIC_DOMAIN}
        ports:
            - "${PUBLIC_ADDRESS}:53306:3306"
        restart: 'always'
        volumes: 
            - 'db:/var/lib/mysql'
            - 'db_logs:/var/log/mysql'
        environment:
            MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
            MYSQL_DATABASE: "${MYSQL_DATABASE}"
            MYSQL_USER: "${MYSQL_USER}"
            MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
volumes:
    db: 
        name: "requisigner-data"
    srv:
        name: "requisigner-web"
    jms: 
        name: "requisigner-jms"
    docs: 
        name: "requisigner-docs"
    w1_logs: {}
    db_logs: {}
    redis_logs: {}
    shared_uds: 
        name: "requisigner-uds"